version: '3.8'

services:
  phone-socket-server:
    build: 
      context: .
      dockerfile: PhoneSocketServer/Dockerfile
    container_name: phone_socket_server
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    networks:
      - phone_network

  # For development with hot reload
  phone-socket-server-dev:
    build: 
      context: .
      dockerfile: PhoneSocketServer/Dockerfile
      target: build
    container_name: phone_socket_server_dev
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - .:/src
    command: dotnet watch run --project PhoneSocketServer/PhoneSocketServer.csproj
    networks:
      - phone_network
    profiles:
      - dev

networks:
  phone_network:
    driver: bridge
